export interface Notice {
  name: string;
  subject: string;
  notice: string;
  creation: string;
  modified: string;
  modified_by: string;
  owner: string;
  docstatus: number;
  idx: number;
  type_of_notifications: string;
  html: string | null;
  student: string;
  student_first_name: string;
  student_status: string;
  school: string;
  class: string;
  division: string | null;
  academic_year: string;
  is_generic_notice: number;
  is_raw_html: number;
  is_read: number;
  is_archived: number;
  is_stared: number;
  test: string | null;
  _user_tags: string | null;
  _comments: string | null;
  _assign: string | null;
  _liked_by: string | null;
}
